# Generated by Django 5.1.1 on 2024-09-29 20:41

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('live_site_url', models.CharField(max_length=1024)),
                ('git_repository_url', models.CharField(max_length=1024)),
                ('year', models.CharField(max_length=4)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('html', 'html'), ('css', 'css'), ('javascript', 'javascript'), ('python', 'python'), ('django', 'django'), ('react', 'react'), ('stripe', 'stripe')], max_length=46)),
                ('position', models.IntegerField(unique=True)),
            ],
        ),
    ]
